#+TITLE: Company in Emacs
#+OPTIONS: num:6

* Introduction
/Auto-completion/ is an important functionality in Emacs. It can greatly speed up our editing and programming. Generally speaking, the auto-completion can be divided into two parts, /frontend/ and /backend/. As their names indicate, the former presents interface, while the latter provides contents. In a nutshell, the backend generates completion contents and feeds them to the frontend; then the frontend presents completion candidates to us for selection.

Up to now, there are a couple of popular frontends, /auto-complete/[fn:2] and /company/[fn:1]. "Company" stands for "complete anything". In fact, their functionalities are very similar. Both of them work well and their developments are fairly active. Both of them come with a variety of built-in backends. What deserves attention, for company, we can customize our own backends.

For myself, I have been using company. Its installation and configuration are briefly summarized in this blog.
* Installation
Company can be directly installed via ELPA.
#+BEGIN_SRC emacs-lisp
M-x package-install
company
#+END_SRC
For C/C++ programming, =company-clang= is an excellent backend, it can provide company with the completion candidates based on the analysis and parsing from /clang/.

Addtionally, following two packages can be installed.
- company-c-headers :: It enables clang to access the system headers, i.e. =/usr/include= and =/usr/local/include=.
- company-auctex :: It feeds company the completion from /auctex/[fn:3].
* Configuration
#+BEGIN_SRC emacs-lisp
(global-company-mode 1)
(setq company-idle-delay -1)
(setq company-backends (delete 'company-semantic company-backends))
(add-to-list 'company-backends 'company-c-headers)
(company-auctex-init)
#+END_SRC
Given a project, in order to enable completion based on the 3rd party libaries. A Emacs-Lisp script =.dir-locals.el= can be created and placed in the root of the project. Taking IT++ for instace, the content of =.dir-locals.el= can be listed below.
#+BEGIN_SRC emacs-lisp
((nil . ((company-clang-arguments . ("-I/opt/itpp/include")))))
#+END_SRC

* Footnotes

[fn:3] Auctex is also emacs package, and can be installed via ELPA.

[fn:2] https://github.com/auto-complete/auto-complete

[fn:1] https://github.com/company-mode/company-mode
