#+TITLE: C++ - Basic

本文是阅读 /Professional C++, third edition/ 中文版[fn:1]的读书笔记.

* 预处理指令
- 预处理指令以#字符开始. 如 =#pragma once= 可以防止文件被包含多次.
- 头文件最常见的用途是声明在其他地方定义的函数.
* 函数
- 函数声明通常称为"函数原型"或"签名", 以强调其代表函数的访问方式, 而不是具体的代码.
- 函数参数的默认值只能存在于函数声明中, 不能放在函数定义中.
- 与C不同, 在C++中没有形参的函数仅需要一个空的圆括号, 不需要使用 =void= 指出此处没有形参. 然而, 如果没有返回值, 仍需要使用 =void= 来指明这一点.
- =main()= 函数是程序的入口. =main()= 函数返回一个 =int= 值以指示程序的最终执行状态. =main()= 函数或者没有参数, 或者具有两个参数.
#+BEGIN_SRC c++
  int main(int argc, char* argv[])
#+END_SRC
- 自C++11以来, C++通过拖尾返回类型(trailing return type)支持一种替代的函数语法. 函数的返回类型不再位于开头, 而放在行尾的箭头 =->= 后面. 这在指定模板函数的返回类型时非常有用.
#+BEGIN_SRC c++
  auto func(int i) -> int
  {
      return i + 1;
  }
#+END_SRC
- C++14允许要求编译器自动推断出函数的返回类型. 为此, 需要指定返回类型为 =auto=, 并忽略所有拖尾返回类型.
* 类型推断
类型推断允许编译器自动推断出表达式的类型. 类型推断有两个关键字: =auto= 和 =decltype=.
** =auto=
- 告诉编译器, 在编译时自动推断变量的类型.
- 用于替代函数语法.
- 用于函数返回类型的推断.
- 用于通用的 =lambda= 表达式.
** =decltype=
- 关键字 =decltype= 把表达式作为实参, 可以计算出该表达式的类型.
- 使用 =auto= 推断表达式的类型, 就不需要引用限定符和 =const= 限定符了. C++14引入了 =decltype(auto)= 来解决这个问题.
* 指针
- 堆是与当前函数或堆栈帧完全没有关系的内存区域. 如果想在函数调用结束之后仍然保存其中声明的变量, 可以将变量放到堆中.
- 在C++中, 应避免C中的 =malloc()= 和 =free()=, 而使用 =new= 和 =delete=, 或者 =new[]= 和 =delete[]=. 每次调用 =new/new[]=, 都必须相应地调用 =delete/delete[]= 确保释放(删除)在堆上分配的任何内存以避免内存泄漏. 此外, 最好将指针重置为 =nullptr=, 这并非强制要求, 但这样做可以防止在删除内存后意外使用这个指针. 这个过程不会自动完成, 除非使用了智能指针.
- 在任何时候都应避免使用未初始化的变量, 尤其是未初始化的指针, 因为它们会指向内存中的每个随意位置. 使用这种指针很可能导致程序崩溃. 因此, 必须显式地同时声明和初始化指针. 如果不希望立即分配内存, 可以将其初始化为空指针(nullptr).
- 从技术角度看, 如果指针指向某个结构, 可以首先用 =*= 对指针解除引用, 然后使用 =.= 访问结构中的字段. 箭头运算符 =->= 允许同时对指针解除引用并访问字段.
** 智能指针
为了避免常见的内存问题, 应使用智能指针替代通常C风格的"裸"指针. 智能指针是指向动态分配内存的一个指针, 当超出作用域时(如在函数执行完毕后), 会自动释放内存. C++中有如下三种智能指针, 定义在头文件 =<memory>= 中.
- =std::unique_ptr= :: 通用的智能指针, 可以指向任意类型的内存, 是一个模板. 自从C++14以来, 可以使用 =std::make_unique<>()= 创建. 在尖括号中必须指定 =unique_ptr= 要指向的内存类型.
- =std::shared_ptr= :: 可以使用 =std::make_shared<>()= 创建.
- =std::weak_ptr= :: 
* 名称空间
- =::= 称为作用域解析运算符.
- =using= 指令可以用来引用名称空间的所有项或者特定项.
- 切勿在头文件中使用 =using= 指令或者 =using= 声明.
* 数组
- 在C++中声明数组时, 必须声明数组的大小. 数组的大小不能用变量来表示--必须用常量或常量表达式(constexpr)来表示数组大小.
- 数组也可以用初始化列表来初始化, 此时编译器可以自动推断出数组的大小.
- C++有一种大小固定的特殊容器 =std::array=, 定义在 =<array>= 头文件中, 其具有迭代器, 可以方便地遍历元素. 必须在尖括号中指定两个参数, 第一个表示数组中元素的类型, 第二个参数表示数组的大小.
* 字符串
- 在C语言中, 字符串表示为字符的数组. 字符串中的最后一个字符是空字符(=\0=), 官方将这个空字符定义为 =NUL=. 这样, 操作字符串的代码就知道字符串在哪里结束.
- 与字面量(literal)关联的真正内存在内存的只读部分中.
- 原始字符串字面量(raw string literal)是可以跨越多行代码的字符串字面量, 形式为 =R"d(character sequence)d"=, 其中 =d= 表示分隔符序列, 无歧义(字符串字面量中无特殊符号, 如 ="=)时可以省略.
- C++的 =string= 类定义在 =std= 名称空间的头文件 =<string>= 中. 此外, C++还包含了一些来自C语言的字符串操作函数, 定义在头文件 =<cstring>= 中.
- 为了兼容, 可以使用 =string= 的 =c_str()= 方法获得一个表示C风格字符串的 =const= 字符指针. 不过, 一旦 =string= 对象被销毁或执行了任何内存重分配, 这个返回的 =const= 字符指针就失效了.
- 数值转换
#+BEGIN_SRC c++
  // Transformation to string
  string to_string(int val);
  string to_string(unsigned val);
  string to_string(long val);
  string to_string(unsigned long val);
  string to_string(long long val);
  string to_string(unsigned long long val);
  string to_string(float val);
  string to_string(double val);
  string to_string(long double val);

  // Transformation from string
  int stoi(const string &str, size_t *idx = 0, int base = 10);
  long stol(const string &str, size_t *idx = 0, int base = 10);
  unsigned long stoul(const string &str, size_t *idx = 0, int base = 10);
  long long stoll(const string &str, size_t *idx = 0, int base = 10);
  unsigned long long stoll(const string &str, size_t *idx = 0, int base = 10);
  float stof(const string &str, size_t *idx = 0, int base = 10);
  double stof(const string &str, size_t *idx = 0, int base = 10);
  long double stof(const string &str, size_t *idx = 0, int base = 10);
#+END_SRC
* =switch=
在 =switch= 语句中, 表达式必须是整型或能转换为整型的类型, 必须与一个常量进行比较.
* 基于区间的 =for= 循环
基于区间的 =for= 循环(range-based for loop)允许方便地迭代容器中的元素. 这种循环类型可以用于C风格的数组, 初始化列表, 也可以用于具有返回迭代器的 =begin()= 和 =end()= 函数的类型, 如 =std::array= 和其他所有STL容器.
#+BEGIN_SRC c++
  std::array<int, 3> arr = {1, 2, 3};
  for (int i : arr)
      std::cout << i << std::endl;
#+END_SRC
* 异常
当某段代码检测到异常时, 就会抛出一个异常. 另一段代码会捕获这个异常并执行相应的操作.
* =const=
1. 取代 =#define= 定义常量.
2. 保护参数(如引用参数).
3. 在类的定义中, 最好将不改变对象的任何数据成员的成员函数声明为 =const=.

* 面向对象思想
面向对象编程(object oriented programming, OOP)的基本观念不是将程序分割为若干任务, 而是将其分为自然对象的模型.
** 对象之间的关系
- "有一个(has a)" :: "有一个"关系或者聚合关系的模式是A有一个B, 或者A包含一个B. 可以认为一个对象是另外一个对象的一部分.
- "是一个(is a)" :: "是一个"关系或者派生或者子类或者扩展或者继承, 表明一种层次关系. 当需要提供相关类型的不同行为时, 应该使用继承.
** 层次结构
优秀的面向对象层次结构能够做到以下几点
- 使类之间存在有意义的功能关系.
- 将共同的功能放入基类, 从而支持代码重用.
- 避免子类过多地重写父类的功能, 除非父类是一个抽象类.
** 抽象
抽象的关键在于有效地分离接口和实现. 实现是用来完成任务的代码, 接口是其他用户使用代码的方式. 优秀的接口只包含公有行为, 类的属性/变量绝不应该是公有, 但是可以通过 =getter= 和 =setter= 公有行为公开.
** 代码重用
- 高聚合 :: 当设计库或者框架时, 应该关注单个任务或者一组任务. 避免组合不相干的概念或者逻辑上独立的概念.
- 低耦合 :: 将子系统设计为可以单独重用的分立组件.
- 模板 :: C++模板的概念允许以类型或者类的形式创建泛型结构. 如果打算为不同的类型提供相同的功能, 或者要创建一个可以存储任何类型的容器, 应该使用模板. 模板不是编写泛型数据结构的唯一机制. 在C和C++中, 可以通过存储 =void*= 指针(而不是特定类型)来编写泛型数据结构. 通过将类型转换为 =void*=, 用户可以用这个结构存储他们想要的任何类型. 然而这不是类型安全的: 容器无法检测或者强迫指定存储元素的类型. 可以将任何类型转换为 =void*=, 存储在这个结构中, 当从这个数据结构中删除指针时, 必须将它们转换为对应的类型.
* 类和对象
** 定义
类可以有许多成员, 可以是成员变量(数据成员), 也可以是成员函数(方法, 构造函数或析构函数). 成员函数和成员变量不能同名. 最好将不改变对象的成员函数声明为 =const=.
** 访问控制
类中的每个方法和成员都可以用如下访问说明符(access specifiers)来说明. 访问说明符将应用于其后声明的所有成员, 直到遇到另一个访问说明符.
- =public= :: 将属性或者行为设置为 =public= 意味着其他代码可以访问它们.
- =protected= :: 意味着其他代码不能访问这个属性或者行为, 但是子类可以访问. 也即, 派生类的成员函数可以调用基类的 =protected= 成员.
- =private= :: 最严格的控制, 意味着不仅其他代码不能访问这个属性或者行为, 子类也不能访问. 也即, 派生类的成员函数不能访问基类的 =private= 成员.

建议不要使用公有数据成员, 应该通过公有的 =getter/setter= 方法来访问. 如果要访问静态数据成员, 应该相应地使用静态的 =getter/setter=.

与类相似, C++中的结构(=struct=)也可以拥有方法. 实际上, 结构与类的唯一区别在于结构的默认访问说明符是 =public=, 而类的默认访问说明符是 =private=.
** =this=
每个普通的方法调用都会传递一个指向对象的指针, 即称为隐藏参数的 =this= 指针.
** 构造函数(=constructor=)
*** 基本概念
当创建对象时(同时也会创建内嵌的对象), 会执行一个构造函数. 从语法上讲, 构造函数是与类同名的方法, 没有返回类型, 可以有也可以没有参数. 没有参数的构造函数称为默认构造函数或者零参数构造函数.
- 在堆栈中创建对象时, 调用默认构造函数不需要使用圆括号.
- 如果没有指定任何构造函数, 编译器将自动生成一个默认构造函数. 然而, 如果声明了构造函数(默认构造函数或者其他构造函数), 编译器就不会再自动生成默认构造函数.
*** 构造函数初始化器
除了构造函数体内, C++还支持在构造函数初始化器中初始化数据成员. 构造函数初始化器出现在构造函数参数列表和构造函数函数体之间, 以冒号开始, 由逗号分隔, 允许在创建数据成员时执行初始化. 值得注意的是, 初始化数据成员的顺序是按照在类定义中出现的顺序, 而不是在构造函数初始化器中的顺序. 

但是, 下列数据类型必须在构造函数初始化器中初始化.
- =const= 数据成员. 因为 =const= 变量创建之后无法对其正确赋值, 所以必须在创建时赋值.
- 引用数据成员. 因为不指向一个量, 引用将无法存在.
- 没有默认构造函数的对象数据成员.
- 没有默认构造函数的基类.
*** 复制构造函数
复制构造函数(copy constructor)是一种特殊的构造函数, 允许所创建的对象是另一个对象的精确副本. 如果没有定义复制构造函数, C++会自动生成一个, 用源对象中相应数据成员的值初始化新对象的每个数据成员. 如果数据成员是对象, 初始化意味着调用它们的复制构造函数.
*** 初始化列表构造函数
初始化列表构造函数将初始化列表作为第一个参数, 并且没有任何其他参数(或者其他参数有默认值). C++11 STL完全支持初始化列表构造函数.

初始化列表 =std::initializer_list<T>= 定义在头文件 =<initializer_list>= 中, 简化了参数数量可变函数的编写. 与变长参数列表不同, 初始化列表中所有的元素都应该是同一种预定义类型. 由于定义了列表中允许的类型, 初始化列表是类型安全的.
*** 类内成员初始化
在C++11之前, 只有在构造函数体内或者构造函数初始化器中才能初始化成员变量, 只有 =static const= 整形成员变量才能在类定义中初始化. 从C++11开始, 允许在定义类时直接初始化成员变量.
*** 委托构造函数
委托构造函数(delegating constructor)允许构造函数调用同一个类的其他构造构造函数. 但是, 该调用不能放在构造函数体内, 而必须放在构造函数初始化器中, 且必须是构造函数初始化列表中唯一的成员初始化器.

当使用委托构造函数是, 要避免出现构造函数的递归, 如两个构造函数互相委托.
*** 编译器自动生成的构造函数
默认构造函数和复制构造函数之间缺少对称性, 即
- 只要定义了任何构造函数, 编译器就不会再自动生成默认构造函数.
- 只要没有显式定义复制构造函数, 编译器就会自动生成一个.

但是, 可以通过定义显式默认构造或者显式删除构造函数, 来影响自动生成的默认构造函数和复制构造函数.
** 析构函数
*** 基本概念
- 析构函数与类(以及构造函数)同名, 前面有一个波浪号(=~=).
- 析构函数没有参数, 并且一个类只能有一个析构函数.
- 通常, 析构函数释放在构造函数中分配的内存. 虽然并没有规则要求这么做, 在析构函数中可以编写任何代码, 但是最好让析构函数只释放内存或者清理其他资源.
- 在构造函数中抛出异常时, 不会调用析构函数.

销毁对象时会发生两件事: 调用对象的析构函数, 释放对象占用的内存. 如果没有声明析构函数, 编译器会自动生成一个, 析构函数会逐一销毁成员, 然后删除对象.

当堆栈中的对象超出作用域时, 意味着当前的函数, 方法或者其他执行代码块结束, 对象会被销毁. 换句话说, 当代码遇到结束花括号时, 这个花括号中所有创建在堆栈上的对象都会被销毁. 堆栈上对象的销毁顺序与声明顺序(也即构建顺序)相反.
** 对象赋值
C++为所有的类提供了赋值的方法, 也即赋值运算符 =operator== (=assignment operator=), 其本质是对类重载了运算符=.
- 如果没有编写自己的赋值运算符, C++将自动生成一个, 从而允许将对象赋给另一个对象. 默认的C++赋值行为几乎与默认的赋值行为相同: 以递归的方式用源对象的每个数据成员赋值给目标对象. 可以显式地默认或者删除编译器生成的赋值运算符.
- 实际上, 可以让赋值运算符返回任意类型, 包括 =void=. 然而, 通常返回被调用对象的引用更有用.
- 赋值运算符的实现与复制构造函数类似, 但两者也存在重要的区别: 复制构造函数只有在初始化时才调用, 此时目标对象还没有有效的值. 赋值运算符可以改写对象的当前值.
- 在类中动态分配内存时, 如果只想禁止其他人复制对象或者为对象赋值, 只需显式地将 =operator== 和复制构造函数标记为 =delete=.
- 无论什么时候, 只要在类中动态分配了内存, 就应该编写自己的析构函数, 复制构造函数和赋值运算符(以提供深层的内存复制).
** 数据成员
*** 静态数据成员
- 静态(=static=)数据成员是属于类而不是对象的数据成员, 可将静态数据成员当作类的全局变量.
- 不仅要在类定义中列出静态成员, 还需要在源文件(通常是定义类方法的那个源文件)中为其分配内存(与声明全局变量类似, 但是需要使用作用域解析运算符 =::=), 还可以对其进行初始化. 与普通的变量和数据成员不同, 在默认情况下, 静态数据成员会初始化为0, 静态指针会初始化为 =nullptr=.
- 在类方法内部, 可以像使用普通数据成员那样使用静态数据成员. 类方法外的访问取决于访问控制限定符: 如果是 =private=, 不能在类方法外访问; 如果是 =public=, 就可以在类方法外访问(需要使用作用域解析运算符 =::=).
*** 常量数据成员
类中的数据成员可以声明为 =const=, 意味着在创建并初始化之后, 数据成员的值不能再改变.
*** 引用数据成员
在初始化一个引用之后, 不能改变它引用的对象. 因此不可能在赋值运算符中对引用赋值. 就像普通引用可以引用常量对象一样, 引用成员也可以引用常量对象.
** 方法
*** =static= 方法
- 静态方法就像一个普通函数, 唯一区别在于这个方法可以访问类的 =private= 和 =protected= 静态数据成员.
- 类中任何方法都可以像调用普通函数那样调用静态方法. 如果要在类的外面调用静态方法, 需要使用类名称和作用域解析运算符来限定方法的名称(就像静态数据成员那样). 静态方法的访问控制和普通方法一样.
- 在方法定义前不需要重复 =static= 关键字.
- 静态方法不属于特定对象, 因此没有 =this= 指针. 当用某个特定对象调用静态方法时, 静态方法不会访问这个对象的非静态数据成员. 
- 如果同一类型的其他对象对于静态方法可见(例如传递了对象的指针或者引用), 静态方法也可以访问其他对象的 =private= 和 =protected= 非静态数据成员.
*** =const= 方法
- 为了保证方法不改变数据成员, 可以用 =const= 关键字标记方法本身. 应该将不修改对象的所有方法声明为 =const=.
- 不能将静态方法声明为 =const=, 因为这是多余的. 静态方法没有类的实例, 因此不可能改变内部的值.
- =const= 的工作原理是将方法内用到的数据成员都标记为 =const= 引用, 因此如果试图修改数据成员, 编译器会报错.
- 非 =const= 对象可以调用 =const= 方法和非 =const= 方法; 然而, =const= 对象只能调用 =const= 方法.
- =const= 也会被销毁, 它们的析构函数也会被调用, 因此不应该将析构函数标记为 =const=.
*** 重载
- 将函数或者方法的名称用于多个函数, 但是参数的类型或者数目不同.
- C++不允许仅根据方法的返回类型重载方法名称, 但是可以根据 =const= 重载方法[fn:2].
- 重载参数可以被显式地删除, 可以用这种方法禁止调用具有特定参数的成员函数.
*** 运算符重载
- 当C++编译器分析一个程序, 遇到运算符(如 +/-/=/<<)时, 就会试着查找名为 operator+/-/=/<<, 且具有适当参数的函数或者方法.
- 在C++中, 无法改变运算符的优先级. 例如, *和/总是在+和-之前求值. 用于定义的运算符唯一能做的就是在运算符优先级已经确定的情况下编写实现. 而且, C++还不允许开发新的运算符符号.
- 运算符重载是函数重载的一种形式. 编译器允许用作 =operator+= 参数的对象类型与编写 =operator+= 的类不同. 也可以任意指定 =operator+= 的返回值类型.
- 当编写运算符重载的对象在运算符的左边时, 可以隐式转换; 但是当对象在运算符右边时, 不能隐式转换. 除非使用全局友元函数.
- 编写了基本运算符(如+和-), 并没有提供相应的简写运算符(如+=和-=). 必须显式地重载简写运算符.
- 简写运算符与基本运算符不同, 它们会改变运算符左边的对象, 而不是创建一个新对象. 它们生成的结果是对被修改对象的引用, 这一点与赋值运算符类似.
- 比较运算符(如>,<,==)与基本的算术运算符类似, 它们也应该是全局友元函数.
*** 默认参数
- 在原型中可以指定函数或者方法的参数默认值.
- 只能从最右边的参数开始提供连续的默认参数列表.
- 默认参数可以用于函数, 方法和构造函数.
- 所有参数都有默认值的构造函数等同于默认构造函数. 如果试图同时声明默认构造函数和有参数但所有参数都有默认值的构造函数, 编译器会报错. 因为如果不指定任何参数, 编译器不知道该调用哪个构造函数.
- 任何默认参数能做到的事情, 都可以用方法重载做到.
*** 内联(=inline=)
- 内联指编译器将方法体或者函数体直接插入到调用方法或者函数的位置.
- 在方法或者函数定义的名称之前使用 =inline= 关键字. 注意, =inline= 关键字仅仅是提示编译器, 如果编译器认为这会降低性能, 就会忽略该关键字.
- 如果编写了内联函数或方法, 应将定义与原型一起放在头文件中.
- C++提供了另一种声明内联函数的语法: 直接将方法定义放在类定义中, 不使用 =inline= 关键字.
*** 友元(=friend=)
- C++允许某个类将其他类, 其他类的成员函数或者非成员函数声明为友元. 友元可以访问类的 =private=, =protected= 数据成员和方法.
- 在函数定义中不需要再使用 =friend= 关键字.
- 友元可以违反封装的原则.
* =lambda= 表达式
=lambda= 表达式可以编写内嵌的匿名函数, 而不必编写独立函数或函数对象, 使代码更容易阅读和理解. =lambda= 表达式以方括号 =[]= 开始, 其后是花括号 ={}=, 其中包含了 =lambda= 表达式体. 完整的语法为
#+BEGIN_SRC c++
  [capture_block] (parameters) mutable exception_specification attribute_specifier -> return_type {body}
#+END_SRC
除 =[capture_block]= 和 ={body}= 外, 其他参数均为可选参数.
- =lambda= 表达式可以接受参数. 参数在圆括号中指定, 用逗号分隔开, 与普通函数相同.
- 如果 =lambda= 表达式不接受参数, 就可以指定空圆括号或忽略它们.
- =lambda= 表达式可以返回值. 返回类型在箭头后面指定, 也即拖尾返回类型. 即使 =lambda= 表达式返回了值, 也可以忽略返回类型, 此时编译器就根据函数返回类型推断规则来推断 =lambda= 表达式的返回类型.
- =lambda= 表达式可以在其封装的作用域内捕捉变量. 方括号部分称为 =lambda= 捕捉块(capture block), 可以指定任何从 =lambda= 表达式所在的作用域中捕捉变量. 这里捕捉变量指可以在 =lambda= 表达式体中使用这个变量. 空白的捕捉块表示不从所在作用域中捕捉变量. 捕捉方式可以是按值捕捉, 也可以按引用捕捉(=lambda= 表达式可以在其内部作用域修改 =lambda= 表达式所在作用域内的变量). 捕捉的对象既可以是所在作用域中的所有变量, 也可以通过捕捉列表酌情捕捉需要的变量以及相应的捕捉方法. 例如:
  + =[=]= :: 通过值捕捉所有变量.
  + =[&]= :: 通过引用捕捉所有变量.
  + =[x]= :: 只通过值捕捉变量 =x=.
  + =[&x]= :: 只通过引用捕捉变量 =x=.
  + =[&, x]= :: 默认通过引用捕捉, 但 =x= 是按值捕捉.
  + =[this]= :: 捕捉周围的对象. 即使没有使用 =this->=, 也可以在 =lambda= 表达式体中访问这个对象.
* Footnotes

[fn:2] 例如可以编写两个名称, 参数均相同的两个方法, 一个是 =const=, 另一个不是. 如果是 =const= 对象, 就调用 =const= 方法; 如果是非 =const= 对象, 就调用非 =const= 方法.

[fn:1] Marc Gregoire著, 张永强译. C++高级编程(第3版), 清华大学出版社, 2015.
