#+TITLE: Emacs - CapsLk as Control

* Background
Usually, key =CapsLk= is seldom used in our daily utilization, while key =Ctrl= is frequently used, esp. for Emacs users. Therefore, we can turn =CapsLk= into an additional =Ctrl=.
* Methods
** Xmodmap
=xmodmap= is a utility for remapping keys in =Xorg=. To turn =CapsLk= into another =Ctrl=, install package =xorg-xmodmap=, e.g.
#+BEGIN_SRC sh
pacman -S xorg-xmodmap
#+END_SRC
and create =~/.Xmodmap= with its contents as follows.
#+BEGIN_SRC sh
clear lock
clear control
keycode 66 = Control_L
add control = Control_L Control_R
#+END_SRC
For display manager, e.g. GDM, KDM, XDM, based startup, that is all. For =startx=-based, add a following entry in =~/.xinitrc=.
#+BEGIN_SRC sh
[[ -f ~/.Xmodmap ]] && xmodmap ~/.Xmodmap
#+END_SRC
** Gnome
Regarding Gnome and KDE, it is extremely easy to turn =CapsLk= into an additional =Ctrl=. Taking Gnome for instance, install package =gnome-tweak-tool=, e.g.
#+BEGIN_SRC sh
pacman -S gnome-tweak-tool
#+END_SRC
and configure it in the installed =Tweak Tool=. Enter =Typing= -> =Caps Lock key behavior= and tick the radio =Caps Lock is also a Ctrl=.
