#+TITLE: Emacs - CapsLock as Ctrl

* Background
Usually, key =CapsLock= is seldom used in our daily utilization, while key =Ctrl= is frequently used, esp. for Emacs users. Therefore, we can turn =CapsLock= into an additional =Ctrl=.
* Methods
** Xmodmap
=xmodmap= is a utility for remapping keys in =Xorg=. To turn =CapsLock= into another =Ctrl=, install package =xorg-xmodmap=, e.g.
#+BEGIN_SRC sh
pacman -S xorg-xmodmap
#+END_SRC
and create =~/.Xmodmap= with its contents as follows.
#+BEGIN_SRC sh
clear lock
clear control
add control = Caps_Lock Control_L Control_R
keycode 66 = Control_L
#+END_SRC
For display manager, e.g. GDM, KDM, XDM, based startup, that is all. For =startx=-based, add a following entry in =~/.xinitrc=.
#+BEGIN_SRC sh
[[ -f ~/.Xmodmap ]] && xmodmap ~/.Xmodmap
#+END_SRC
** Gnome
For Gnome, it is extremely easy to turn =CapsLock= into an additional =Ctrl=. Install package =gnome-tweak-tool=, e.g.
#+BEGIN_SRC sh
pacman -S gnome-tweak-tool
#+END_SRC
and configure it in the installed =Tweak Tool=. Enter =Typing= -> =Caps Lock key behavior= and tick the radio =Caps Lock is also a Ctrl=.
** KDE
For KDE, the transformation can be directly finished in the =system settings=. Enter =Input Devices= -> =Keyboard= -> =Advanced=, and tick the radio =Caps Lock is also a Ctrl= in =Caps Lock behavior= and =Caps Lock as Ctrl= in =Ctrl position=.
