#+TITLE: NR - Demodulation Reference Signal (DMRS)

* Introduction
Just as its name indicates, /demodulation reference signal (DMRS)/ is the reference signal dedicated for demodulation. Different from LTE system, the DMRS in NR system is comprised of a /frontloaded DMRS/ and a few optional /additional DMRS/.
** Frontloaded DMRS
Frontloaded DMRS aims to reduce the duration of demodulation and decoding. There are a couple of mapping schemes.
- /Mapping type A/: it lies the symbol second to the PDCCH region, e.g., in normal-slot-based transmission.
- /Mapping type B/: it begins with the first data symbol scheduled, e.g., in mini-slot-based transmission.
** Additional DMRS
Additional DMRS is proposed to support high speed transmission, e.g., 500km/h. Each additional DMRS is a simple repetition of the corresponding frontloaded DMRS, e.g., identical subcarriers and equal OFDM symbol number.
- For single-symbol frontloaded DMRS, up to 3 additional DMRS can be supported.
- For double-symbol frontloaded DMRS, at most 1 additional DMRS is supported.
* Sequence Generation
DMRS symbols are a sequence of QPSK-modulated Gold sequence, which is initialized with
\[
c_{\text{init}} = \left[ 2^{17}(N_{\text{symb}}^{\text{slot}}n_{s,f}^{\mu} + \ell + 1)(2N_{\text{ID}}^{n_{\text{SCID}}}+1) + 2N_{\text{ID}}^{n_{\text{SCID}}} + n_{\text{SCID}} \right] \mod 2^{31}
\]
where
* Layer Number
** SU-MIMO
Up to 8 or 4 layers can be supported for downlink and uplink transmission, respectively.
** MU-MIMO
Irrespective of downlink or uplink, up to 12 layers can be supported for MU-MIMO, with at most 4 layers for each user.
* Pattern
In NR system, there are two types of DMRS, a.k.a., type-1 and type-2.
- For CP-OFDM, both types are supported[fn:1].
- For DFT-S-OFDM, only type-1 is supported.
** Type-1
- In single-symbol case, up to 4 ports are supported.
  + 2x comb (corresponding to /CDM groups 0 and 1/)
  + 2x frequency domain orthogonal cover code (OCC)[fn:2]
- In double-symbol case, up to 8 ports are supported.
  + 2x comb (corresponding to CDM groups 0 and 1)
  + 2x frequency-domain OCC[fn:2]
  + 2x time-domain OCC
** Type-2
- In single-symbol case, up to 6 ports are supported.
  + 3x FDM (corresponding to /CDM groups 0, 1, and 2/)
  + 2x frequency domain OCC
- In double-symbol case, up to 12 ports are supported.
  + 3x FDM (corresponding to CDM groups 0, 1, and 2)
  + 2x frequency domain OCC
  + 2x time domain OCC

* Footnotes

[fn:2] For OCC code \([1, -1]\) with 2x comb, it is essentially a cyclic shift of \(\dfrac{N_{FFT}}{4}\), corresponding to a phase rotation of \(\dfrac{\pi}{2}\).

[fn:1] DMRS types are configured by a high layer parameter. Before configuration, type-1 DMRS is applied by default.
