#+TITLE: NR - Demodulation Reference Signal (DMRS)

* Introduction
Just as its name indicates, /demodulation reference signal (DMRS)/ is the reference signal dedicated for demodulation. Different from LTE system, the DMRS in NR system is comprised of a /frontloaded DMRS/ and a few optional /additional DMRS/.
** Frontloaded DMRS
Frontloaded DMRS aims to reduce the duration of demodulation and decoding.
- It lies second to the PDCCH region in normal-slot-based transmission.
- It begins with the first data symbol scheduled in mini-slot-based transmission.
** Additional DMRS
Additional DMRS is proposed to support high speed transmission, e.g., 500km/h. Each additional DMRS is a simple repetition of the corresponding frontloaded DMRS, e.g., identical subcarriers and equal OFDM symbol number.
- For single-symbol frontloaded DMRS, up to 3 additional DMRS can be supported.
- For double-symbol frontloaded DMRS, at most 1 additional DMRS is supported.
* Layer Number
** SU-MIMO
Up to 8 or 4 layers can be supported for downlink and uplink transmission, respectively.
** MU-MIMO
Irrespective of downlink or uplink, up to 12 layers can be supported for MU-MIMO, with at most 4 layers for each user.
* Pattern
In NR system, there are two types of DMRS, a.k.a., type-1 and type-2.
- For CP-OFDM, both types are supported[fn:1].
- For DFT-S-OFDM, only type-1 is supported.
** Type-1
- In single-symbol case, up to 4 ports are supported.
  + Comb x2
  + Frequency domain orthogonal cover code (OCC) x2
- In double-symbol case, up to 8 ports are supported.
  + Comb x2
  + Frequency domain OCC x2
  + Time domain OCC x2
** Type-2
- In single-symbol case, up to 6 ports are supported.
  + Frequency division multiplex (FDM) x3
  + Frequency domain OCC x2
- In double-symbol case, up to 12 ports are supported.
  + FDM x3
  + Frequency domain OCC x2
  + Time domain OCC x2

* Footnotes

[fn:1] DMRS types are configured by a high layer parameter. Before configuration, type-1 DMRS is applied by default.
