#+title: Python - Pandas

=Pandas= 支持大部分 =numpy= 语言风格的数组计算。尽管代码风格相似，但最大的不同在于前者是用来处理表格或不同类型数据的，而后者更适合处理相同类型数据的。

* 数据结构
** Series
- =Series= 是一维数组的对象，包含 =index= 序列和 =values= 序列，分别可以通过对象的 =index= 和 =values= 属性获得。
- 通常需要创建一个index序列来标识每个数据点。如果不显式指定，那么默认 =index= 为从0到N-1，其中N为Series对象的长度。
- =index= 可以用来索引数据，在这种意义上， =Series= 就像一个有序的字典。 另外，可以通过字典直接生成 =Series= 对象。
- =pandas= 用 =NaN (not a number)= 来标记缺失或NA值，用 =isnull= 和 =notnull= 函数来检查 =Series= 对象。同时， =isnull= 和 =notnull= 也是 =Series= 类的成员函数。
** DataFrame
- =DataFrame= 是二维数据表，既有行索引，又有列索引。可以通过属性 =T= 进行转置。每一列可以是不同的类型（数值、字符串、布尔值等）。
- 和 =Series= 类似， =DataFrame= 的 =values= 属性会将数据以二维ndarray形式返回。
- 虽然 =DataFrame= 是二维的，但是可以通过分层索引扩展到更高维度的数据。
- 成员函数 =head()= 返回前五行。
- 成员函数 =set_index= (参数可以为单个列名或多个列名的列表) 将选中的列转换为索引。
- 成员函数 =filter(regex=KEYWORD)= 可以通过正则表达式对列名进行过滤筛选，返回一个符合筛选条件的新 =DataFrame= 。
- 成员函数 =plot= 可以直接调用 =matplotlib= 绘图。默认地，以索引作为x轴，各个数据列为y轴，列名作为图例名称。但是其行为可以定制。例如，
  #+begin_src python
    df.plot(ax=AX, x=COL1_NAME, y=COL2_NAME, title=TITLE, xlabel=XLABEL, ylabel=YLABEL, grid=True/False, legend=True/False, linestyle=LINESTYLE, xlim=[XMIN, XMAX], ylim=[YMIN, YMAX])
  #+end_src
- =DataFrame= 对象可以通过行索引返回 =Series= 对象。也即 =DataFrame.loc['index_name']= 。
- =DataFrame= 对象可以通过列索引返回 =Series= 对象。也即 =DataFrame['column_name']= ，如果列名无效，那么会新建列。此外， =DataFrame.column_name= 也能达到相同目的，但仅当列名存在时才有效时。值得注意的是，索引的列是数据的视图，而不是拷贝。因此，对返回 =Series= 对象的修改会映射到 =DataFrame= 对象。如果需要复制，需要调用 =Series= 类的 =copy= 成员函数。
- 在将列表或数组赋值给某一列时，列表或数组的长度必须和 =DataFrame= 对象的长度相等。将 =Series= 对象赋值给某一列时， 其索引会按照 =DataFrame= 对象的索引重新排序，并用缺失值填充空缺位置。
** 索引对象
- =Pandas= 中的索引对象是用于存储轴标签和其他元数据的。构建 =Series= 或 =DataFrame= 对象时所使用的数组或标签序列都可以在内部转换为索引对象。
- 索引对象是不可变的，不能修改。
* 基本功能
- =reindex= : 重建索引。
- =drop= : 删除行或列。
- =concat= : 合并多个Series或DataFrame。例如，
  #+begin_src python
    import pandas as pd

    df = pd.concat([df1, df2], axis=1)
  #+end_src
* 输入输出
- =read_csv=
  #+begin_src python
    import pandas as pd

    df = pd.read_csv(FILENAME, [skiprows=N], [names=[COL1, COL2, COL3, ...]], [index_col=[0, 1]])
  #+end_src
- =to_csv=
