#+TITLE: Wiener-Khinchin Theorem

* Wiener-Khinchin Theorem
Given a /wide-sense stationary (WSS)/ stochastic process, its autocorrelation function and its power spectral density function are a pair of Fourier transform.
* Frequency domain correlation
The frequency domain correlation can be derived as
\begin{align}
  \mathcal{E}\left[ H(f_1) H^{*}(f_2) \right] &= \mathcal{E} \left[ \int_{-\infty}^{+\infty}h(\tau_1)e^{-j2\pi f_1\tau_1} d\tau_1 \cdot \int_{-\infty}^{+\infty}h^{*}(\tau_2)e^{j2\pi f_2\tau_2} d\tau_2 \right] \nonumber \\
                                              &= \int_{-\infty}^{+\infty} \int_{-\infty}^{+\infty} \mathcal{E}\left[ h(\tau_1)h^{*}(\tau_2)\right]e^{-j2\pi(f_1 \tau_1 - f_2 \tau_2)} d\tau_1 d\tau_2, \label{eq:corr-f}
\end{align}
where $h(\tau)$ and $H(f)$ are the /channel impulse response (CIR)/ and /channel frequency response (CFR)/ of the channel, respectively.

If the individual paths of the channel are uncorrelated, i.e., /uncorrelated scatering (US)/, $\mathcal{E}\left[h(\tau_1) h^{*}(\tau_2)\right] = h(\tau_1) h^{*}(\tau_2) \delta(\tau_1 - \tau_2)$, then equation \eqref{eq:corr-f} can be further written as
\begin{align}
\mathcal{E}\left[ H(f_1) H^{*}(f_2) \right] &= \int_{-\infty}^{+\infty}|h(\tau)|^2 e^{-j2\pi(f_1-f_2)\tau}d\tau \nonumber \\
&=\int_{-\infty}^{+\infty}P_{\mathrm{delay}}(\tau) e^{-j2\pi(f_1-f_2)\tau}d\tau, \label{eq:corr-f-us}
\end{align}
where $P_{\mathrm{delay}}(\tau) \triangleq |h(\tau)|^2$ is the /power delay profile (PDP)/ of the channel.

Particularly, if PDP is uniformly distributed within /cyclic prefix (CP)/, denoted by $L_{\mathrm{cp}}$, i.e.,
\begin{align*}
P_{\mathrm{delay}}(\tau) &= \frac{1}{L_{\mathrm{cp}}}, \quad \tau \in [0, L_{\mathrm{cp}}]; \\
\mathcal{E}\left[ H(f_1) H^{*}(f_2) \right] &=\mathrm{sinc} \left[ \left( f_1 - f_2 \right)L_{\mathrm{cp}} \right] e^{-j\pi\left( f_1 - f_2 \right)L_{\mathrm{cp}}}.
\end{align*}
* Temporal domain correlation
Without loss of generality, we consider a frequency-flat fading channel for instance, and the channel can be represented as
\begin{align}
  h(t) = \int_0^{2\pi} a(\theta)e^{j2\pi f_m t \cos\theta} d\theta, \label{eq:h-t}
\end{align}
where $a(\theta)$ is the complex-valued gain of the ray arrived in the direction of $\theta$, and $f_m \triangleq \dfrac{v}{\lambda}$ is termed /maximum Doppler frequency/.

Then, the temporal domain correlation can be expressed as
\begin{align}
  \mathcal{E}\left[h(t_1)h^{*}(t_2)\right] &= \mathcal{E}\left[ \int_0^{2\pi} a(\theta_1)e^{j2\pi f_m t_1 \cos\theta_1} d\theta_1 \cdot \int_0^{2\pi} a^{*}(\theta_2)e^{-j2\pi f_m t_2 \cos\theta_2} d\theta_2\right] \nonumber \\  &=\int_0^{2\pi}\int_0^{2\pi}\mathcal{E}\left[a(\theta_1)a^{*}(\theta_2)\right]e^{j2\pi f_m(t_1\cos\theta_1 - t_2\cos\theta_2)}d\theta_1 d\theta_2\label{eq:corr-t}.
\end{align}
For US, similarly, we have $\mathcal{E}\left[a(\theta_1)a^{*}(\theta_2)\right] = a(\theta_1)a^{*}(\theta_2)\delta(\theta_1-\theta_2)$, and equation \eqref{eq:corr-t} becomes
\begin{align}
  \mathcal{E}\left[h(t_1)h^{*}(t_2)\right] &= \int_0^{2\pi} |a(\theta)|^2 e^{j2\pi f_m (t_1-t_2)\cos\theta} d\theta \nonumber \\
  &= \int_0^{2\pi}P_{\mathrm{angle}}(\theta) e^{j2\pi f_m (t_1-t_2)\cos\theta} d\theta \label{eq:corr-t-us-angle} \\
&= \int_{-f_m}^{f_m} P_{\mathrm{doppler}}(f)e^{j2\pi f(t_1-t_2)} df, \label{eq:corr-t-us-doppler}
\end{align}
where $P_{\mathrm{angle}}(\theta) \triangleq |a(\theta)|^2$ is the /power angle spectrum/ of the channel, and $P_{\mathrm{doppler}}(f) \triangleq 2P_{\mathrm{angle}}(\theta) \left|\dfrac{d\theta}{df}\right| = \dfrac{2P_{\mathrm{angle}}(\theta)}{\sqrt{f_m^2 - f^2}}$ is the well-known /Doppler power spectrum/ of the channel.

Particularly, if all the arriving paths are uniformly around the receiver, a.k.a. /uniform ring scattering/ in Clarke model, we have
\begin{align*}
P_{\mathrm{angle}}(\theta) &= \frac{1}{2\pi}, \quad \theta \in [0,2\pi); \\
P_{\mathrm{doppler}}(f) &= \frac{1}{\pi \sqrt{f_m^2 - f^2}}, \quad f \in [-f_m, f_m]; \\
\mathcal{E}\left[h(t_1)h^{*}(t_2)\right] &= J_0 \left[ 2\pi f_m(t_1-t_2) \right],
\end{align*}
where $J_0(\cdot)$ is the zero-order Bessel function of the first kind. Accordingly, the Doppler power spectrum becomes U-shaped.
* Spatial domain correlation
Without loss of generality, we consider a uniform antenna array housing $N$ antenna elements spaced by $d$. The spatial-domain channel can be denoted by
\begin{align}
  \mathbf{h} = \int_0^{2\pi} a(\theta) \mathbf{v}(\theta) d\theta,
\end{align}
where $a(\theta)$ is a complex-valued amplitude of a path in the direction of $\theta$, and $\mathbf{v}(\theta)$ is the corresponding steering vector, i.e.,
\begin{align}
\mathbf{v}(\theta) = 
\begin{bmatrix}
1 \\ e^{{jkd\cos\theta}} \\ e^{j2kd\cos\theta} \\ \vdots \\ e^{j(N-1)kd\cos\theta}
\end{bmatrix},
\end{align}
where $k\triangleq \dfrac{2\pi}{\lambda}$ is the wave number and $\lambda$ the wave length. Then, the spatial domain correlation can be derived as
\begin{align}
  \mathcal{E}\left[ \mathbf{h}(n_1) \mathbf{h}^{*}(n_2) \right] &= \mathcal{E} \left[ \int_{0}^{2\pi} a(\theta_1) e^{jn_1kd\cos\theta_{1}} d\theta_{1}\cdot \int_{0}^{2\pi} a^{*}(\theta_{2}) e^{-jn_2kd\cos\theta_{2}} d\theta_{2}\right]; \quad 0 \leq n_1, n_2 \leq N-1; \nonumber \\
&= \int_{0}^{2\pi}\int_{0}^{2\pi} \mathcal{E} \left[a(\theta_1)a^{*}(\theta_2) \right]e^{jkd(n_1\cos\theta_{1} - n_2\cos\theta_{2})} d\theta_{1}d\theta_{2}. \label{eq:corr-s}
\end{align}

Similarly, in US case, we have $\mathcal{E}\left[a(\theta_{1}) a^{*}(\theta_{2}) \right]=a(\theta_{1}) a^{*}(\theta_{2}) \delta(\theta_{1}-\theta_{2})$, and equation \eqref{eq:corr-s} becomes
\begin{align}
  \mathcal{E}\left[ \mathbf{h}(n_1) \mathbf{h}^{*}(n_2) \right] &= \int_0^{2\pi}|a(\theta)|^2 e^{jk(n_1-n_2)d\cos\theta} d\theta \nonumber \\
&= \int_0^{2\pi} P_{\mathrm{angle}}(\theta)e^{jk(n_1-n_2)d\cos\theta} d\theta.
\end{align}
Particularly, for uniform ring scattering, we have
\begin{align*}
  P_{\mathrm{angle}}(\theta) &= \frac{1}{2\pi}, \quad \theta \in [0, 2\pi); \\
  \mathcal{E}\left[ \mathbf{h}(n_1) \mathbf{h}^{*}(n_2) \right] &= J_0 \left[ k(n_1-n_2)d \right].
\end{align*}
