#+TITLE: Linux - Zsh

* Introduction
As is well-known, /shell/ is an interface provided by the Unix/Linux operation systems (OS) to subscribers whereby a user can interact with the kernel of the OS efficiently and conveniently.

In fact, there are already a variety of shells, e.g., bash, csh, tcsh, zsh, etc. This post just presented a brief introduction to /zsh/.

Zsh is indeed a powerful shell. Perhaps this is just the reason why it is termed "shell terminator", as letter 'Z' is the letter terminator, the last one in the alphabeta.
* Installation
For Archlinux, zsh can be easily installed by the following command.
#+BEGIN_SRC sh
  pacman -S zsh
#+END_SRC
* Configuration
** Mandatory
After the installation, zsh can be made as the default shell by
#+BEGIN_SRC sh
  chsh -s /bin/zsh
#+END_SRC
Before that, all the shells available can be listed by
#+BEGIN_SRC sh
  chsh -l
#+END_SRC
Then, you can add your own configuration in =~/.zshrc=.
** Optional
Even though zsh is usable out of the box, future configuration is necessary since the customization can really improve our experiences.

Regarding the customization, there exists a toolkit already, e.g., =oh-my-zsh=, which can be considered as a baseline for the further configuration.

Here is an example =~/.zshrc=.
#+BEGIN_SRC sh
  # Lines configured by zsh-newuser-install
  setopt notify
  unsetopt beep
  bindkey -e
  # End of lines configured by zsh-newuser-install

  [[ $TERM=="xterm" ]] && export TERM=xterm-256color

  # If you come from bash you might have to change your $PATH.
  # export PATH=$HOME/bin:/usr/local/bin:$PATH

  # Path to your oh-my-zsh installation.
  export ZSH=/usr/share/oh-my-zsh

  # Set name of the theme to load. Optionally, if you set this to "random"
  # it'll load a random theme each time that oh-my-zsh is loaded.
  # See https://github.com/robbyrussell/oh-my-zsh/wiki/Themes
  ZSH_THEME="robbyrussell"

  # Uncomment the following line to use case-sensitive completion.
  # CASE_SENSITIVE="true"

  # Uncomment the following line to use hyphen-insensitive completion. Case
  # sensitive completion must be off. _ and - will be interchangeable.
  # HYPHEN_INSENSITIVE="true"

  # Uncomment the following line to disable bi-weekly auto-update checks.
  DISABLE_AUTO_UPDATE="true"

  # Uncomment the following line to change how often to auto-update (in days).
  # export UPDATE_ZSH_DAYS=13

  # Uncomment the following line to disable colors in ls.
  # DISABLE_LS_COLORS="true"

  # Uncomment the following line to disable auto-setting terminal title.
  # DISABLE_AUTO_TITLE="true"

  # Uncomment the following line to enable command auto-correction.
  # ENABLE_CORRECTION="true"

  # Uncomment the following line to display red dots whilst waiting for completion.
  # COMPLETION_WAITING_DOTS="true"

  # Uncomment the following line if you want to disable marking untracked files
  # under VCS as dirty. This makes repository status check for large repositories
  # much, much faster.
  # DISABLE_UNTRACKED_FILES_DIRTY="true"

  # Uncomment the following line if you want to change the command execution time
  # stamp shown in the history command output.
  # The optional three formats: "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
  # HIST_STAMPS="mm/dd/yyyy"

  # Would you like to use another custom folder than $ZSH/custom?
  # ZSH_CUSTOM=/path/to/new-custom-folder

  # Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
  # Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
  # Example format: plugins=(rails git textmate ruby lighthouse)
  # Add wisely, as too many plugins slow down shell startup.
  plugins=(git)


  # User configuration

  # export MANPATH="/usr/local/man:$MANPATH"

  # You may need to manually set your language environment
  # export LANG=en_US.UTF-8

  # Preferred editor for local and remote sessions
  # if [[ -n $SSH_CONNECTION ]]; then
  #   export EDITOR='vim'
  # else
  #   export EDITOR='mvim'
  # fi
  export EDITOR='emacs -nw'

  # Compilation flags
  # export ARCHFLAGS="-arch x86_64"

  # ssh
  # export SSH_KEY_PATH="~/.ssh/rsa_id"

  # Set personal aliases, overriding those provided by oh-my-zsh libs,
  # plugins, and themes. Aliases can be placed here, though oh-my-zsh
  # users are encouraged to define aliases within the ZSH_CUSTOM folder.
  # For a full list of active aliases, run `alias`.
  #
  # Example aliases
  # alias zshconfig="mate ~/.zshrc"
  # alias ohmyzsh="mate ~/.oh-my-zsh"
  alias ls='ls --color=auto'
  alias e='/usr/bin/emacs -nw'
  alias sudo='sudo '

  ZSH_CACHE_DIR=$HOME/.oh-my-zsh-cache
  if [[ ! -d $ZSH_CACHE_DIR ]]; then
      mkdir $ZSH_CACHE_DIR
  fi

  source $ZSH/oh-my-zsh.sh

#+END_SRC
